apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-config
data:
  ASPNETCORE_ENVIRONMENT: Development
  ConnectionStrings__ProductDb: "Server=db;Database=Products;User Id=sa;Password=Djxtian20"